apiVersion: v1
kind: Namespace
metadata:
  name: web
  labels:
   name: web
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: deployment
  namespace: web
  labels:
    app: web
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: wildapplications/webapp:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: web
spec:
  type: LoadBalancer
  loadBalancerIP: 35.195.25.85
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: web
  externalName: web
